export const styles = {
    body: {
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      minHeight: '100vh',
      padding: '20px',
    },
    container: {
      maxWidth: '1200px',
      margin: '0 auto',
    },
    header: {
      textAlign: 'center',
      marginBottom: '40px',
      color: 'white',
    },
    headerTitle: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '15px',
      marginBottom: '10px',
    },
    logo: {
      fontSize: '50px',
      background: 'white',
      padding: '15px',
      borderRadius: '15px',
      boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    },
    h1: {
      fontSize: '48px',
      fontWeight: '700',
      textShadow: '2px 2px 4px rgba(0,0,0,0.3)',
    },
    subtitle: {
      fontSize: '18px',
      opacity: '0.9',
    },
    cardContainer: {
      display: 'flex',
      flexDirection: 'column',
      gap: '30px',
    },
    card: {
      background: 'white',
      borderRadius: '20px',
      padding: '30px',
      boxShadow: '0 10px 40px rgba(0,0,0,0.1)',
    },
    emergencyCard: {
      background: 'linear-gradient(135deg, #fff5f5 0%, #ffe5e5 100%)',
      borderRadius: '20px',
      padding: '30px',
      boxShadow: '0 10px 40px rgba(0,0,0,0.1)',
      border: '3px solid #feb2b2',
    },
    cardHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '15px',
      marginBottom: '25px',
      paddingBottom: '15px',
      borderBottom: '2px solid #f0f0f0',
    },
    cardIcon: {
      fontSize: '32px',
      padding: '12px',
      borderRadius: '12px',
    },
    iconBlue: { background: '#ebf4ff' },
    iconGreen: { background: '#e6f7ed' },
    iconRed: { background: '#ffe6e6' },
    cardTitle: {
      fontSize: '24px',
      fontWeight: '700',
      color: '#2d3748',
    },
    formGroup: {
      marginBottom: '20px',
    },
    label: {
      display: 'block',
      fontSize: '14px',
      fontWeight: '600',
      color: '#4a5568',
      marginBottom: '8px',
    },
    input: {
      width: '100%',
      padding: '12px 16px',
      border: '2px solid #e2e8f0',
      borderRadius: '10px',
      fontSize: '15px',
      transition: 'all 0.3s',
      fontFamily: 'inherit',
    },
    textarea: {
      resize: 'vertical',
      minHeight: '100px',
    },
    checkboxGroup: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      padding: '15px',
      background: '#fff5f5',
      border: '2px solid #feb2b2',
      borderRadius: '10px',
      marginBottom: '20px',
    },
    checkbox: {
      width: 'auto',
      margin: '0',
      cursor: 'pointer',
    },
    checkboxLabel: {
      margin: '0',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      color: '#c53030',
      fontWeight: '600',
      fontSize: '14px',
    },
    button: {
      width: '100%',
      padding: '14px 20px',
      border: 'none',
      borderRadius: '10px',
      fontSize: '16px',
      fontWeight: '600',
      cursor: 'pointer',
      transition: 'all 0.3s',
      boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
      color: 'white',
    },
    btnBlue: {
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    },
    btnGreen: {
      background: 'linear-gradient(135deg, #48bb78 0%, #38a169 100%)',
    },
    btnOrange: {
      background: 'linear-gradient(135deg, #ed8936 0%, #dd6b20 100%)',
    },
    btnRed: {
      background: 'linear-gradient(135deg, #f56565 0%, #e53e3e 100%)',
    },
    grid2: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '20px',
    },
    results: {
      marginTop: '25px',
    },
    resultsTitle: {
      fontSize: '18px',
      fontWeight: '600',
      color: '#2d3748',
      marginBottom: '15px',
    },
    resultItem: {
      padding: '15px',
      background: '#f7fafc',
      borderLeft: '4px solid #48bb78',
      borderRadius: '8px',
      marginBottom: '10px',
      color: '#2d3748',
    },
    otpDisplay: {
      padding: '20px',
      background: '#fef5e7',
      border: '3px solid #f39c12',
      borderRadius: '10px',
      margin: '20px 0',
      textAlign: 'center',
    },
    otpLabel: {
      fontSize: '14px',
      color: '#875a00',
      marginBottom: '8px',
    },
    otpValue: {
      fontSize: '32px',
      fontWeight: '700',
      color: '#875a00',
      letterSpacing: '4px',
    },
    alertError: {
      padding: '15px',
      borderRadius: '10px',
      marginTop: '15px',
      fontWeight: '500',
      background: '#fed7d7',
      border: '2px solid #fc8181',
      color: '#c53030',
    },
    alertWarning: {
      padding: '15px',
      borderRadius: '10px',
      marginTop: '15px',
      fontWeight: '500',
      background: '#feebc8',
      border: '2px solid #f6ad55',
      color: '#c05621',
    },
    criticalInfo: {
      marginTop: '20px',
    },
    criticalItem: {
      padding: '15px',
      background: 'white',
      borderLeft: '4px solid #f56565',
      borderRadius: '8px',
      marginBottom: '10px',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    },
    footer: {
      textAlign: 'centxer',
      marginTop: '40px',
      color: 'white',
      opacity: '0.8',
    },
  };
